apply plugin: "com.vanniktech.maven.publish"

mavenPublish {
    releaseSigningEnabled = false
    publishing {
        repositories {
            maven {
                credentials {
                    username '60e6b7fe3c458713ddbf2d80'
                    password 'VMuNtiaI9Ygh'
                }
                url 'https://packages.aliyun.com/60e6b812f00dfa2fa4cac307/maven/2119527-release-1nbpdv'
            }
        }
    }
}